package first.greatsky.entity;

import com.alibaba.fastjson.JSON;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table banner
 */
public class Banner implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column banner.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * Database Column Remarks:
	 * Banner名称，通常作为标识
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column banner.name
	 *
	 * @mbg.generated
	 */
	private String name;

	/**
	 * Database Column Remarks:
	 * Banner描述
	 * <p>
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column banner.description
	 *
	 * @mbg.generated
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column banner.delete_time
	 *
	 * @mbg.generated
	 */
	private Integer deleteTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column banner.update_time
	 *
	 * @mbg.generated
	 */
	private Integer updateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table banner
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column banner.id
	 *
	 * @return the value of banner.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column banner.id
	 *
	 * @param id the value for banner.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column banner.name
	 *
	 * @return the value of banner.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column banner.name
	 *
	 * @param name the value for banner.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column banner.description
	 *
	 * @return the value of banner.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column banner.description
	 *
	 * @param description the value for banner.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column banner.delete_time
	 *
	 * @return the value of banner.delete_time
	 * @mbg.generated
	 */
	public Integer getDeleteTime() {
		return deleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column banner.delete_time
	 *
	 * @param deleteTime the value for banner.delete_time
	 * @mbg.generated
	 */
	public void setDeleteTime(Integer deleteTime) {
		this.deleteTime = deleteTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column banner.update_time
	 *
	 * @return the value of banner.update_time
	 * @mbg.generated
	 */
	public Integer getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column banner.update_time
	 *
	 * @param updateTime the value for banner.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Integer updateTime) {
		this.updateTime = updateTime;
	}

	public String toString() {

		return JSON.toJSONString(this);
	}

}