package first.greatsky.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table banner_item
 */
public class bannerItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   外键，关联image表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.img_id
     *
     * @mbg.generated
     */
    private Integer imgId;

    /**
     * Database Column Remarks:
     *   执行关键字，根据不同的type含义不同
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.key_word
     *
     * @mbg.generated
     */
    private String keyWord;

    /**
     * Database Column Remarks:
     *   跳转类型，可能导向商品，可能导向专题，可能导向其他。0，无导向；1：导向商品;2:导向专题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.delete_time
     *
     * @mbg.generated
     */
    private Integer deleteTime;

    /**
     * Database Column Remarks:
     *   外键，关联banner表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.banner_id
     *
     * @mbg.generated
     */
    private Integer bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_item.update_time
     *
     * @mbg.generated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table banner_item
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.id
     *
     * @return the value of banner_item.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.id
     *
     * @param id the value for banner_item.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.img_id
     *
     * @return the value of banner_item.img_id
     *
     * @mbg.generated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.img_id
     *
     * @param imgId the value for banner_item.img_id
     *
     * @mbg.generated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.key_word
     *
     * @return the value of banner_item.key_word
     *
     * @mbg.generated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.key_word
     *
     * @param keyWord the value for banner_item.key_word
     *
     * @mbg.generated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.type
     *
     * @return the value of banner_item.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.type
     *
     * @param type the value for banner_item.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.delete_time
     *
     * @return the value of banner_item.delete_time
     *
     * @mbg.generated
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.delete_time
     *
     * @param deleteTime the value for banner_item.delete_time
     *
     * @mbg.generated
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.banner_id
     *
     * @return the value of banner_item.banner_id
     *
     * @mbg.generated
     */
    public Integer getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.banner_id
     *
     * @param bannerId the value for banner_item.banner_id
     *
     * @mbg.generated
     */
    public void setBannerId(Integer bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_item.update_time
     *
     * @return the value of banner_item.update_time
     *
     * @mbg.generated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_item.update_time
     *
     * @param updateTime the value for banner_item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}